
COLLECTION_DECLARATION:
    COLLECTION_HEADER { COLLECTION_CODE }

COLLECTION_HEADER:
    ACCESS_MODIFIER collection identifier
    ACCESS_MODIFIER collection identifier implements NOT_EMPTY_COMMA_SEPARATED_IDENTIFIERS_LIST

COLLECTION_CODE:
    COLLECTION_MEMBERS_DECLARATION_ZONE COLLECTION_IMPLEMENTATION

COLLECTION_MEMBERS_DECLARATION_ZONE:
    COMMA_SEPARATED_COLLECTION_MEMBERS_DECLARATION_LIST ;

COLLECTION_IMPLEMENTATION:
    \0
    MEMBER_VARIABLE_DECLARATION COLLECTION_IMPLEMENTATION
    CONSTRUCTOR COLLECTION_IMPLEMENTATION
    MEMBER_FUNCTION_DECLARATION COLLECTION_IMPLEMENTATION

COMMA_SEPARATED_COLLECTION_MEMBERS_DECLARATION_LIST:
    \0
    identifier
    identifier ( ARG_LIST )
    identifier , COMMA_SEPARATED_COLLECTION_MEMBERS_DECLARATION_LIST
    identifier ( ARG_LIST ) , COMMA_SEPARATED_COLLECTION_MEMBERS_DECLARATION_LIST


