/* function declarations only. */


CONSTRUCTOR:

CLASS_MEMBER_FUNCTION_DECLARATION:
    ACCESS_MODIFIER ABSTRACTION ATOMICITY META_LEVEL function identifier ( FUNC_DEC_ARG_LIST) returns FUNCTION_RETURN_OPTIONS FUNCTION_CODE


FUNCTION_RETURN_OPTIONS:
    BROAD_TYPE
    nothing

FUNCTION_CODE:
    ;
    { STATEMENTS }
    { STATEMENTS } SAME_AS_SEGMENT


SAME_AS_SEGMENT:
    same_as BROAD_EXPRESSION ;



