
INTERFACE_DECLARATION:
    INTERFACE_HEADER { INTERFACE_CODE }

INTERFACE_HEADER:
    ACCESS_MODIFIER interface BROAD_IDENTIFIER IMPLEMENTATION_PART

IMPLEMENTATION_PART:
    \0
    implements NOT_EMPTY_COMMA_SEPARATED_BROAD_IDENTIFIERS_LIST


