
CLASS_MEMBER_VARIABLE_DECLARATION:



COMMON_VARIABLE_DECLARATION:



META_VARIABLE_DECLARATION:





BROAD_TYPE:
    PRIMITIVE
    identifier
    ARRAY_TYPE
    identifier < NON_EMPTY_COMMA_SEPARATED_BROAD_TYPE_LIST >

ARRAY_TYPE:
    BROAD_TYPE NON_EMPTY_CONCATENATED_SQUARE_BRACKETS_LIST

NON_EMPTY_CONCATENATED_SQUARE_BRACKETS_LIST:
    []
    [] NON_EMPTY_CONCATENATED_SQUARE_BRACKETS_LIST

NON_EMPTY_COMMA_SEPARATED_BROAD_TYPE_LIST:
    BROAD_TYPE
    BROAD_TYPE , NON_EMPTY_COMMA_SEPARATED_BROAD_TYPE_LIST